"""add profile_image to users

Revision ID: 305b975416bb
Revises: 1c279d981ef5
Create Date: 2025-06-08 19:22:19.483310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305b975416bb'
down_revision = '1c279d981ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
